In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [2]:

def display(A,B):
    maxX = A.shape[0]
    maxY = A.shape[1]
    
    m2 = np.max(B)
    B[A[:,:]==1] = m2
    
    m1 = np.min(B[B[:,:]>0])
    if(m1==m2): m1=m2/2
    B[B[:,:]==0] = m1*(m1/m2)**(1/10)
    
    D = np.zeros((maxY, maxX))
    for ix in range(0,maxX):
        for iy in range(0,maxY):
            D[maxY-1-iy,ix] = np.log(B[ix, iy])
    %matplotlib qt 
    
    plt.rcParams['figure.figsize'] = [6, 6/maxX*maxY]
    plt.imshow(D); 
    plt.axis('off'); 
    plt.show()
    plt.draw()
    plt.pause(0.1)

In [3]:
nParticles = 10000
maxX = 200+5*9
maxY = 40

In [25]:
A = np.zeros((maxX, maxY))
B = np.zeros((maxX, maxY))


A[:,0] = 1 #adding row at bottom 
A[:, maxY-1] = 1 #adding row at top

print(A)


[[1. 0. 0. ... 0. 0. 1.]
 [1. 0. 0. ... 0. 0. 1.]
 [1. 0. 0. ... 0. 0. 1.]
 ...
 [1. 0. 0. ... 0. 0. 1.]
 [1. 0. 0. ... 0. 0. 1.]
 [1. 0. 0. ... 0. 0. 1.]]


In [5]:
#particle starts in the middle at very right of pipe 

ystart = maxY//2
xstart = maxX-1

In [9]:
def F(A,B):
    finished = 0 
    for i in range (0,nParticles):
        x = xstart
        y = ystart;

    #movement probabilities

        while True:
            xorg = x
            yorg = y

            r = np.random.random();
            if r>0.5:
                x = x-1
            elif r>0.4:
                x = x+1
            elif r>0.2:
                y = y+1
            else:
                y = y-1

    #boundary conditions 

            if (x >= maxX-1): #bouncing off right boundary 
                x = xorg
                y = yorg
                continue;

            #determining neighboring coords     
            xp = x+1
            xm = x-1
            yp = y+1
            ym = y-1

            if ym < 0:
                ym = maxY-1
            elif yp >= maxY:
                yp = 0
            elif xp >= maxX:
                xp = 0
                
                
            if (xm < 0  or A[xp,y] == 1 or A[xm,y] == 1 or A[x,yp] == 1 or A[x,ym] == 1):
                B[x,y] += 1
                
                if xm<1:
                    finished += 1
                if (i%1000==0 and i != 0): 
                    current_prob = finished/i #calc of prob at given interval 
                    print(f'i= {i}\tx={x} \ty={y} \tyStart={ystart} \tCurrent probability={current_prob}')

                if i%1000 == 0:
                    display(A,B)
                
                break 
            
    return finished, current_prob
            

            
finished, current_prob = F(A,B)
print('Particles Finished',finished)

prob_finished = finished/nParticles
print('probability Finished', prob_finished)

accuracy = (abs(current_prob - prob_finished)/prob_finished)*100
print('accuracy (%)',accuracy)

display(A,B)
plt.savefig('final.png', bbox_inches='tight')
            

i= 1000	x=0 	y=14 	yStart=20 	Current probability=0.533
i= 2000	x=120 	y=1 	yStart=20 	Current probability=0.5295
i= 3000	x=0 	y=23 	yStart=20 	Current probability=0.5296666666666666
i= 4000	x=0 	y=34 	yStart=20 	Current probability=0.531
i= 5000	x=0 	y=11 	yStart=20 	Current probability=0.5366
i= 6000	x=0 	y=15 	yStart=20 	Current probability=0.5388333333333334
i= 7000	x=107 	y=1 	yStart=20 	Current probability=0.5375714285714286
i= 8000	x=178 	y=38 	yStart=20 	Current probability=0.537875
i= 9000	x=99 	y=38 	yStart=20 	Current probability=0.5353333333333333
Particles Finished 5353
probability Finished 0.5353
accuracy (%) 0.0062270377981187485


In [31]:
A = np.zeros((maxX, maxY))
B = np.zeros((maxX, maxY))

r = 5

A1 = np.copy(A)

for i in range(maxX):
    for j in range(maxY):
        A1[:,0] = 1 #adding row at bottom 
        A1[:, maxY-1] = 1 #adding row at top'
        if (i-(maxX/2))**2+(j-(maxY/2))**2 <= r**2 or (i-(maxX/2)-20)**2+(j-(maxY/2))**2 <= r**2 or (i-(maxX/2)+20)**2+(j-(maxY/2))**2 <= r**2:
            A1[i,j] = 1
            
plt.imshow(A1)

        


In [32]:
#question 6, 3 circles 
            
finished, current_prob = F(A1,B)
print('Particles Finished',finished)

prob_finished = finished/nParticles
print('probability Finished', prob_finished)

accuracy = (abs(current_prob - prob_finished)/prob_finished)*100
print('accuracy (%)',accuracy)

display(A1,B)
plt.savefig('final.png', bbox_inches='tight')
            

i= 1000	x=146 	y=24 	yStart=20 	Current probability=0.055
i= 2000	x=148 	y=18 	yStart=20 	Current probability=0.061
i= 3000	x=0 	y=26 	yStart=20 	Current probability=0.06333333333333334
i= 4000	x=192 	y=1 	yStart=20 	Current probability=0.06625
i= 5000	x=129 	y=1 	yStart=20 	Current probability=0.0656
i= 6000	x=119 	y=1 	yStart=20 	Current probability=0.06683333333333333
i= 7000	x=0 	y=32 	yStart=20 	Current probability=0.06714285714285714
i= 8000	x=144 	y=25 	yStart=20 	Current probability=0.066125
i= 9000	x=181 	y=38 	yStart=20 	Current probability=0.06722222222222222
Particles Finished 670
probability Finished 0.067
accuracy (%) 0.3316749585406282


In [40]:
#question 7, shrinking 3 circles in y direction 
A = np.zeros((maxX, maxY))
B = np.zeros((maxX, maxY))


ai = 5
bj = 5/2
#eqs of elipse i^2/a^2 + j^2/b^2 = 1

A2 = np.copy(A)

for i in range(maxX):
    for j in range(maxY):
        A2[:,0] = 1 #adding row at bottom 
        A2[:, maxY-1] = 1 #adding row at top'
        if ((i-(maxX/2))**2)/ai**2+((j-(maxY/2))**2)/bj**2 <= 1 or ((i-(maxX/2)-20)**2)/ai**2+((j-(maxY/2))**2)/bj**2 <= 1 or ((i-(maxX/2)+20)**2)/ai**2+((j-(maxY/2))**2)/bj**2 <= 1: 
            A2[i,j] = 1
            
plt.imshow(A2)

In [41]:
finished, current_prob = F(A2,B)
print('Particles Finished',finished)

prob_finished = finished/nParticles
print('probability Finished', prob_finished)

accuracy = (abs(current_prob - prob_finished)/prob_finished)*100
print('accuracy (%)',accuracy)

display(A2,B)
plt.savefig('final.png', bbox_inches='tight')

#success prob increased due to less surface area of obstacles in the main direction of particle travel (-x)

i= 1000	x=104 	y=38 	yStart=20 	Current probability=0.131
i= 2000	x=171 	y=1 	yStart=20 	Current probability=0.1325
i= 3000	x=148 	y=21 	yStart=20 	Current probability=0.13033333333333333
i= 4000	x=104 	y=38 	yStart=20 	Current probability=0.13375
i= 5000	x=118 	y=38 	yStart=20 	Current probability=0.1304
i= 6000	x=145 	y=17 	yStart=20 	Current probability=0.127
i= 7000	x=145 	y=23 	yStart=20 	Current probability=0.12842857142857142
i= 8000	x=147 	y=18 	yStart=20 	Current probability=0.127875
i= 9000	x=148 	y=21 	yStart=20 	Current probability=0.12655555555555556
Particles Finished 1264
probability Finished 0.1264
accuracy (%) 0.12306610407875607


In [44]:
#question 8, enlarging obstacles in X direction by factor of 2

ai = 5*2
bj = 5
#eqs of elipse i^2/a^2 + j^2/b^2 = 1

A3 = np.copy(A)

for i in range(maxX):
    for j in range(maxY):
        A3[:,0] = 1 #adding row at bottom 
        A3[:, maxY-1] = 1 #adding row at top'
        if ((i-(maxX/2))**2)/ai**2+((j-(maxY/2))**2)/bj**2 <= 1 or ((i-(maxX/2)-20)**2)/ai**2+((j-(maxY/2))**2)/bj**2 <= 1 or ((i-(maxX/2)+20)**2)/ai**2+((j-(maxY/2))**2)/bj**2 <= 1: 
            A3[i,j] = 1
            
plt.imshow(A3)

In [45]:
finished, current_prob = F(A3,B)
print('Particles Finished',finished)

prob_finished = finished/nParticles
print('probability Finished', prob_finished)

accuracy = (abs(current_prob - prob_finished)/prob_finished)*100
print('accuracy (%)',accuracy)

display(A3,B)
plt.savefig('final.png', bbox_inches='tight')


i= 1000	x=151 	y=23 	yStart=20 	Current probability=0.041
i= 2000	x=150 	y=24 	yStart=20 	Current probability=0.046
i= 3000	x=148 	y=38 	yStart=20 	Current probability=0.048
i= 4000	x=151 	y=23 	yStart=20 	Current probability=0.04875
i= 5000	x=152 	y=18 	yStart=20 	Current probability=0.0488
i= 6000	x=151 	y=23 	yStart=20 	Current probability=0.049833333333333334
i= 7000	x=147 	y=25 	yStart=20 	Current probability=0.05014285714285714
i= 8000	x=150 	y=24 	yStart=20 	Current probability=0.050875
i= 9000	x=153 	y=20 	yStart=20 	Current probability=0.051
Particles Finished 506
probability Finished 0.0506
accuracy (%) 0.7905138339920901


In [ ]:
#this is similar to the prob of the orginal circles due to it having the same width in the y direction, 
#the width chnage in x direction only slightly decreased the prob due to paricles moving mostly in the x direction. 
#change in y width causes the most variation, as seen in question 6 prob 