# Diffusion Limited Aggregation 
#lab 06


In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [2]:
#note, this function expects a matrix A[ix,iy] 
#and then displays so that A[:,0] is the lowest row of pixels
def display(A):
    maxX = A.shape[0]
    maxY = A.shape[1]
    B = np.zeros((maxY, maxX))
    for ix in range(0,maxX):
        for iy in range(0,maxY):
            B[maxY-1-iy,ix] = A[ix,iy]

    #Display the graphics outside of the notebook. 
    #On a PC, use '%matplotlib qt' instead.
    %matplotlib qt 
    
    plt.rcParams['figure.figsize'] = [6, 6/maxX*maxY]
    plt.imshow(B); 
    plt.axis('off'); 
    plt.show()
    plt.draw()
    plt.pause(0.01)

In [3]:
nParticles = 10000
maxX = 500
maxY = 300

In [4]:
# Initialize matrix containing all 2D grid points A(x,y)
# 0 <= x < maxX
# 0 <= y < maxY
# A(x,y)=0 ... site is empty
# A(x,y)>0 ... site is filled
A = np.zeros((maxX, maxY))

# Introduce a sticky wall at the bottom 
# by filling the lowest row of pixels with particles
A[:,0] = 1
print(A.transpose())

[[1. 1. 1. ... 1. 1. 1.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [5]:
#test the display routine
display(A)

In [6]:
# To save computer time, we want to inject the new particle not too far
# above growing aggregate. We inject at on a line 'yStart', which
# keeps being increased so that it is always 'yBuffer' lines above the
# highest structure
yBuffer = 5
yStart  = 1 + yBuffer

In [7]:
for i in range(0,nParticles):
    # Compute new starting point on the line y=yStart
    x  = np.random.randint(0,maxX)
    y  = yStart; #always start at upper limit

    while True:
        xOrg = x
        yOrg = y

        r = np.random.random(); # Random float:  0.0 <= r < 1.0
        #based on the value of 'r', move the particle
        #left, right, up, or down and change x and y accordingly

#spliting 1 into 4 equal parts and assigning a portion to move in 4 differnt directions
        if r>0.75:
            y = y-1
        elif r>0.5:
            x = x-1
        elif r>0.25:
            y = y+1
        else:
            x = x+1
        
        #now apply periodic boundary conditions to 'x'
#REVISIT CONCEPT
        x = x%maxX
        
        
        if (A[x,y] == 1 or y>yStart): 
            x = xOrg
            y = yOrg
            continue; # if this site has been taken try moving in a different direction
        
        #determine the x coordionates of the left and right neighbors
        #store them in 'xm' and 'xp' and apply periodic boundary conditions again
        
 #REVISIT CONCEPT       
        xp = A[(x+1)%maxX,y]
        xm = A[(x-1)%maxX,y]
        yp = A[x, (y+1)]
        ym = A[x,(y-1)]
 
        # Determine if any neighboring site is occupied
        # if that is the case, enter the following 'if' clause
        
#REVISIT CONCEPT
        if np.any(np.array([xp,xm,yp,ym])==1): 
            A[x,y] = 1
            if (y+yBuffer>yStart and y+yBuffer<maxY): 
                yStart = y+yBuffer

            if (i%1000==0): 
                print(f'i= {i} \tx={x} \ty={y} \tyStart={yStart}')

            nNewParticlesPerFrame = 1000 
            if (i%nNewParticlesPerFrame==0): 
                display(A)
                
            break # particle was attached, break out of current loop and insert next one
            
    if (yStart+1==maxY): 
        print(f'Structures reached Y limit after only {i} particles')
        break

display(A)
        

i= 0 	x=143 	y=1 	yStart=6
i= 1000 	x=240 	y=9 	yStart=22
i= 2000 	x=308 	y=23 	yStart=37
i= 3000 	x=63 	y=38 	yStart=50
i= 4000 	x=66 	y=56 	yStart=65
i= 5000 	x=405 	y=70 	yStart=83
i= 6000 	x=3 	y=79 	yStart=95
i= 7000 	x=354 	y=102 	yStart=112
i= 8000 	x=13 	y=113 	yStart=126
i= 9000 	x=18 	y=114 	yStart=137


In [ ]:
#part 2
# adjust so x+1 = 40% prob and x-1 = 10% prob 

#part 3 